language: node_js

node_js:
  - "8.9"

notifications:
  email: false

script:
  - "npm run build"

local-dir:
  "build"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
