language: node_js

node_js:
  - "8.9"

notifications:
  email: false

script: gulp build

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: build
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
